### ISSUE TITLE
Add ODS credentials as environment variables to server

### ISSUE THREAD

**Issue by emaadali** [bostoncollege/CTE-Cohort-Scheduler#3]
Get credentials from `idesdev2.bc.edu/dev/ods_test.php` and add them as environment variables on `idesstage2.bc.edu`

**Comment by walkerjamie** [comment]
I have added a .env file (in public...could be moved to /app) and copied current app.php db settings in. They are not formatted yet but I need your preference for how they should be passed (string/value pairs in 2 separate arrays?). We can then set the container['settings'] properties according to the getenv() call in app.php.

**Comment by walkerjamie** [comment]
pushed changed app.php and relocated .env and .env.template (no values) to app root (out of /public)
